name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Import the blueprint
      run: ./00-importBlueprint.ps1 -subscriptionId ${{ INPUT_SUBSCRIPTIONID }} -blueprintPath ${{ INPUT_BLUEPRINTPATH }} -blueprintName ${{ INPUT_BLUEPRINTNAME }} -spnId ${{ INPUT_SPNID }} -spnPass ${{ INPUT_SPNPASS }} -tenantId ${{ INPUT_TENANTID }}
      shell: pwsh
      with:
        subscriptionId: fa971420-4388-457a-ac56-1cd453785f14
        blueprintPath: ./infrastructure
        blueprintName: testBluePrint
        spnId: 529a5a8d-4dc4-4f1a-9d4f-3ba5f130446f
        spnPass: ${{ secrets.spnPass }}
        tenantId: eb73c9bc-7f90-4841-9556-c3a56cc82c79
