name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Import the blueprint
      env:
        SUBSCRIPTIONID: fa971420-4388-457a-ac56-1cd453785f14
        BLUEPRINTPATH: ./infrastructure
        BLUEPRINTNAME: testBluePrint
        SPNID: 529a5a8d-4dc4-4f1a-9d4f-3ba5f130446f
        SPNPASS: ${{ secrets.spnPass }}
        TENANTID: eb73c9bc-7f90-4841-9556-c3a56cc82c79
      run: ./00-importBlueprint.ps1
      shell: pwsh
    - name: Publish the blueprint
      env:
        SUBSCRIPTIONID: fa971420-4388-457a-ac56-1cd453785f14
        BLUEPRINTPATH: ./infrastructure
        BLUEPRINTNAME: testBluePrint
        SPNID: 529a5a8d-4dc4-4f1a-9d4f-3ba5f130446f
        SPNPASS: ${{ secrets.spnPass }}
        TENANTID: eb73c9bc-7f90-4841-9556-c3a56cc82c79
        VERSION: 6.0.0
      run: ./01-publishBlueprint.ps1
      shell: pwsh
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Assign the blueprint
      env:
        SUBSCRIPTIONID: fa971420-4388-457a-ac56-1cd453785f14
        ASSIGNMENTFILE: ./infrastructure
        BLUEPRINTNAME: testBluePrint
        SPNID: 529a5a8d-4dc4-4f1a-9d4f-3ba5f130446f
        SPNPASS: ${{ secrets.spnPass }}
        TENANTID: eb73c9bc-7f90-4841-9556-c3a56cc82c79
        VERSION: 6.0.0
      run: ./02-assignBlueprint.ps1
      shell: pwsh
